/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_rtf_ffmpeg_JNI */

#ifndef _Included_com_rtf_ffmpeg_JNI
#define _Included_com_rtf_ffmpeg_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_rtf_ffmpeg_JNI
 * Method:    invokeMethod
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_rtf_ffmpeg_JNI_invokeMethod
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
