#!/bin/bash

echo "# 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free
# deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free
deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free
# deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free

deb http://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free
# deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free

deb http://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free
# deb-src https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free" > /etc/apt/sources.list

apt update
#echo "deb [trusted=yes] http://10.15.0.115:8085/kylin_pool/kylin-V10Desktop-pool/KYLIN-ALL 10.1 main universe multiverse restricted" > /etc/apt/sources.list
#echo "deb [trusted=yes] http://10.15.0.115:8085/uos_pool/arm64_desktop/ shangyu main non-free" > /etc/apt/sources.list
#echo "deb [trusted=yes] http://10.15.0.129/opencv buster main " > /etc/apt/sources.list
#echo "deb [trusted=yes] http://10.15.0.129/hjjuosarm shangyu main " >> /etc/apt/sources.list
#echo "deb [trusted=yes] http://10.15.0.129/local buster main " >> /etc/apt/sources.list
#echo "deb [trusted=yes] http://10.15.0.129/hjjuosarm shangyu main " >> /etc/apt/sources.list
#echo "deb [trusted=yes] http://archive.kylinos.cn/kylin/KYLIN-ALL 10.1 main universe multiverse restricted" > /etc/apt/sources.list

#echo "deb [trusted=yes]  http://mirrors.tuna.tsinghua.edu.cn/debian/ stable main contrib non-free" > /etc/apt/sources.list
#echo "deb  [trusted=yes] http://mirrors.tuna.tsinghua.edu.cn/debian/ stretch-updates main contrib non-free" >> /etc/apt/sources.list
#echo "deb [trusted=yes]  http://mirrors.tuna.tsinghua.edu.cn/debian/ stretch-backports main contrib non-free" >> /etc/apt/sources.list
#echo "deb [trusted=yes]  http://mirrors.tuna.tsinghua.edu.cn/debian-security stretch/updates main contrib non-free" >> /etc/apt/sources.list
#echo "deb [trusted=yes] http://mirrors.tuna.tsinghua.edu.cn/debian buster main non-free contrib" >> /etc/apt/sources.list


#cat > /etc/apt/preferences.d/local-pin-900<<EOF
#Package:  *
#Pin: release v=1.0
#Pin-Priority: 2000
#EOF
#
#apt-get -y update
#apt-get -y dist-upgrade --allow-downgrades
#apt install -y gdal-bin libgdal-dev gdal-data
